# Generated by Django 6.1 on 2026-09-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posted_by',
            field=models.CharField(default='dev', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=300),
        ),
    ]
